# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ServiceNow-DevOps-Server-Artifact-Registration@1
  inputs:
    connectedServiceName: 'srecon21-cassandra-ServiceNow DevOps Service Connection'
    artifactRegistrationPayload: |
      {
         "artifacts": [
            {
               "name": "frontend",
               "version": "1.0.$(build.buildId)",
               "semanticVersion": "1.0.$(build.buildId)",
               "repositoryName": "cassandra"
            }
         ],
         "pipelineName": "$(system.teamProject)/$(build.definitionName)",
         "taskExecutionNumber": "$(build.buildId)",
         "stageName": "$(system.jobDisplayName)",
         "attemptNumber": "$(system.jobAttempt)",
         "branchName": "$(build.sourceBranchName)"
      }
    artifactToolIdExists: false
