# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - none
# - master

trigger:
  branches:
    include:
    - build

variables:

  ### Variables ###
  serviceMap: '$(REPO_PREFIX)'

pool:
  vmImage: ubuntu-latest

stages:

  #### Build Image Stage ####
  - stage: Build_All_Images
    jobs:
      - job: Build_All_Images
        steps:
        - bash: |
            set -x # Echo Commands
            # Builld All Images
            cd hack/
            REPO_PREFIX=anthonyangelo TAG=latest ./make-docker-images.sh
          displayName: 'Building All Images...'