# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - none
# - master

trigger:
  branches:
    include:
    - build

variables:

  ### Variables ###
  key1: 'value1'
  key2: 'value2'
  key3: 'value3'    

pool:
  vmImage: ubuntu-latest

stages:

  #### Build Image Stage ####
  - stage: Build_Image
    jobs:
      - job: Build_Image
        steps:
        - script: |
            cd hack/
            ls -la
          displayName: 'Building Image...'