# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:

  ### Variables ###
  repoUserName: '$(REPOUSERNAME)'
  repoPAT: '$(REPOPAT)'
  repoPrefix: '$(REPOPREFIX)'

pool:
  vmImage: ubuntu-latest # This is the default if you don't specify a pool or vmImage.
stages:

  #### Build Image Stage ####
  - stage: Build_All_Images
    jobs:
      - job: Build_All_Images
        steps:
        - bash: |
            set -x # Echo Commands
            # Docker Login
            echo 55354ad5-c1ec-402a-bb77-63cdc1d2e21f | docker login --username ajohnsonls --password-stdin
            # Change Dir
            cd hack/            
            # Build All Images
            REPO_PREFIX=ajohnsonls TAG=latest ./make-docker-images.sh
          displayName: 'Building All Images'