# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - build

variables:

  ### Variables ###
  repoPrefix: $(REPO_PREFIX)
  serviceNamespace: $(SERVICE_NAMESPACE)
  serviceName: $(SERVICE_NAME)

stages:

  #### Register Artifact ####
  - stage: Register_Artifact
    jobs:
      - job: Register_Artifact
        pool: server
        steps:
          - task: ServiceNow-DevOps-Server-Artifact-Registration@1
            inputs:
              connectedServiceName: 'srecon21-cassandra-ServiceNow DevOps Service Connection'
              artifactsPayload: |
                {
                   "artifacts": [
                      {
                         "name": "$(serviceName)",
                         "version": "1.0.$(Build.BuildId)",
                         "semanticVersion": "1.0.$(Build.BuildId)",
                         "repositoryName": "cassandra"
                      }
                   ]
                }

  #### Register Change ####
  - stage: Register_Change
    jobs:
    - job: Register_Change
      pool: server
      steps:
      - task: ServiceNow-DevOps-Server-Change-Acceleration@1
        inputs:
          connectedServiceName: 'srecon21-cassandra-ServiceNow DevOps Service Connection'
          changeRequestDetails: |
            {
                "setCloseCode" : true,
                "attributes": {
                  "cmdb_ci": {
                    "name": "$(serviceName)
                  }
                }
              }

  #### Deploy Image Stage ####
  - stage: Deploy_Image
    jobs:
      - job: Deploy_Image
        steps:
        - bash: |
            set -x # Echo Commands
            # Prem Yaml
            export REPO_PREFIX=$(repoPrefix)
            # Change Dir
            cd src/$(serviceName) 
            # Substitute
            envsubst < ../../kubernetes-manifests/$(serviceName).yaml > ../../kubernetes-manifests/$(serviceName).subst
          displayName: 'Prepping Yaml...'        
        - task: Kubernetes@1
          displayName: 'Deploying $(serviceName) Image...'
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: 'olympus'
            namespace: $(serviceNamespace)
            command: 'apply'
            arguments: '-f kubernetes-manifests/$(serviceName).subst'