# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - none
# - master

trigger:
  branches:
    include:
    - build

variables:

  ### Variables ###
  serviceNamespace: $(SERVICE_NAMESPACE)
  serviceName: $(SERVICE_NAME)

pool:
  vmImage: ubuntu-latest

stages:

  #### Build Image Stage ####
  - stage: Redeploy_Image
    jobs:
      - job: Redeploy_Image
        steps:
        - task: KubernetesManifest@0
          displayName: Patch
          inputs: 
            action: patch
            kind: deployment
            name: demo-5fbc4d6cd9-pgxn4
            mergeStrategy: strategic
            patch: '{"spec":{"containers":[{"name":"demo","image":"foobar/demo:2239"}]}}'
            kubernetesServiceConnection: $(serviceName)
            namespace: $(serviceNamespace)