# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:

  ### Variables ###
  repoUserName: '$(REPO_USERNAME)'
  repoPAT: '$(REPO_PAT)'
  repoPrefix: '$(REPO_PREFIX)'
  serviceName: $(SERVICE_NAME)
  serviceNamespace: $(SERVICE_NAMESPACE)  

pool:
  vmImage: ubuntu-latest

stages:

  #### Build Image Stage ####
  - stage: Build_Image
    jobs:
      - job: Build_Image
        steps:
        - bash: |
            set -x # Echo Commands
            # Docker Login
            echo $(repoPAT) | docker login --username $(repoUserName) --password-stdin        
            # Build Image
            export REPO_PREFIX=$(repoPrefix)
            export TAG=latest
            export IMAGE=$(repoPrefix)/$(serviceName):$TAG
            # Change Dir
            if [ $(serviceName) == "cartservice" ] 
            then
              cd src/$(serviceName)/src
            else
              cd src/$(serviceName)
            fi
            # Build Image   
            docker build -t $IMAGE . && docker push $IMAGE   
          displayName: 'Building Image...'

  #### Deploy Image Stage ####
  - stage: Deploy_Image
    jobs:
      - job: Deploy_Image
        steps:
        - bash: |
            set -x # Echo Commands
            # Prem Yaml
            export REPO_PREFIX=$(repoPrefix)
            # Change Dir
            cd src/$(serviceName) 
            # Substitute
            envsubst < ../../kubernetes-manifests/$(serviceName).yaml > ../../kubernetes-manifests/$(serviceName).subst
          displayName: 'Prepping Yaml...'        
        - task: Kubernetes@1
          displayName: 'Deploying $(serviceName) Image...'
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: 'olympus'
            namespace: $(serviceNamespace)
            command: 'apply'
            arguments: '-f kubernetes-manifests/$(serviceName).subst'          