# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:

  ### Variables ###
  # TBD

pool:
  vmImage: ubuntu-latest

stages:

  #### Run Tests Stage ####
  - stage: Run_Tests
    jobs:
      - job: Run_Tests
        steps:
        - bash: |
            set -x # Echo Commands
            # Install Tools
            pip install -U pytest pytest-html pytest-xdist pytest-nunit
            # Change Dir
            cd tests/frontend
          displayName: 'Running Tests...'