# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

# variables:
  # key1: value1
  # key2: value2
  # key3: value3

pool:
  vmImage: ubuntu-latest

stages:

  #### Run Tests Stage ####
  - stage: Run_Tests
    jobs:
      - job: Run_Tests
        steps:
        - bash: |
            set -x # Echo Commands
            # Install Tools
            pip install -U pytest pytest-html pytest-xdist pytest-nunit
            # Change Dir
            cd tests/frontend
            # Run Tests
            pytest --verbose --nunitxml=TEST-results.xml
      - job: Publish_Tests
        steps:
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'NUnit'
            testResultsFiles: '**/TEST-*.xml'
            searchFolder: '$(System.DefaultWorkingDirectory)/tests/frontend'
            testRunTitle: 'Publish Tests'


